### ISSUE TITLE
Crash on fetching contracts

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/open-balena-api#573]
Hi,

Out of the blue, our API crashed. It's running version 0.109.2.

I've gathered the logs and this is the outcome:
```
Feb 03 11:10:18 openbalena-api-654cd47bb4-sppc2 api[983]: 2021-02-03T11:10:18.681Z 178.62.251.244 a/75 PATCH /device/v2/cdcc2d18cb3d22a5eb24296a0763dd93/state 200 18.022ms -
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]: /usr/src/app/src/features/contracts/contracts-directory.ts:58
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:                 new Error(
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:   ^
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]: Error: Invalid response while fetching contracts: Not Found
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.handleResponse [as _callback] (/usr/src/app/src/features/contracts/contracts-directory.ts:58:3)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.emit (events.js:327:22)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.EventEmitter.emit (domain.js:486:12)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.emit (events.js:327:22)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Request.EventEmitter.emit (domain.js:486:12)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at Object.onceWrapper (events.js:421:28)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at IncomingMessage.emit (events.js:327:22)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at IncomingMessage.EventEmitter.emit (domain.js:486:12)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at endReadableNT (_stream_readable.js:1327:12)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Feb 03 11:10:20 openbalena-api-654cd47bb4-sppc2 api[983]: Program node index.js exited with code 1
```

The API didn't reboot itself, because the container doesn't crash at that time (see issue #383).

**Comment by dfunckt** [comment]
There two issues here:

1. the glitch that caused the NotFound error
2. the fact the exception crashed the process

(1) seems to be due to https://github.com/balena-io/open-balena-api/pull/481/files

(2) has been resolved in https://github.com/balena-io/open-balena-api/pull/539

I suspect this is on an open-balena instance -- merely bumping to open-balena v3.2.0 will pull the fix in.

**Comment by bartversluijs** [comment]
Thanks for your lightning fast response regarding the issue!
I'll update open-balena asap, but because of some changes in the newer version, I'll have to do some tests.
I'll close this issue for now and reopen it if something like this occurs again in the new version!
